### ISSUE TITLE
Add new elements <strong> and <em>

### ISSUE THREAD

**Issue by robander** [oasis-tcs/dita#107]
Stage one proposal: https://lists.oasis-open.org/archives/dita/201803/msg00012.html

Discussed 13 March 2018 and moved to stage 2 with Keith as owner, Kris Eberlein and Bob Thomas as reviewers.

**Comment by keberlein** [comment]
Deb Bissantz r.eplaces Kris as a stage 2 reviewer. Targeted for 12 June.

**Comment by robander** [comment]
Stage 3 reviewers: Bill Burns and Scott Hudson
