### ISSUE TITLE
Split base and technical content

### ISSUE THREAD

**Issue by keberlein** [oasis-tcs/dita#13]
Along with this, improve quality of technical content architectural topics (from DITA 2.0 backlog).
  
Discussed Jan 9 2018: aiming for stage 2 proposal by Feb 12.

06 Feb 2018: Nancy Harrison assigned as reviewer

**Comment by keberlein** [comment]
07 Feb 2017: Moved to stage 2 after discussion at TC meeting.

**Comment by keberlein** [comment]
Discussed an early draft of stage 2 proposal on 9 May 2017. Link to minutes:
https://lists.oasis-open.org/archives/dita/201705/msg00022.html

**Comment by robertnthomas** [comment]
Nancy volunteered to review.

**Comment by robander** [comment]
Splitting base so that it will be published independently of Technical Communications (with Learning and Training also independent) was approved at TC meeting 13 March 2018.

**Comment by robander** [comment]
Marking closed - the tech comm spec is already maintained (and can be published) in its own repo.
