### ISSUE TITLE
Add titlealts elements to map

### ISSUE THREAD

**Issue by robander** [oasis-tcs/dita#16]
Based on proposal from Chris Nitchie here, and several follow-up emails on list:
https://lists.oasis-open.org/archives/dita/201703/msg00030.html

Discussed at TC meeting May 2; moved to Stage 2 and assigned to Chris.
  
Discussed Jan 9 2018: aiming for stage 2 by Feb 19

06 Feb 2018: Bob Thomas assigned as reviewer

**Comment by keberlein** [comment]
Link to minutes from 2 May 2017:
https://lists.oasis-open.org/archives/dita/201705/msg00015.html

**Comment by robander** [comment]
Came up during discussion May 30, 2017, in relation to a proposal to rename `@locktitle`. For now we are not creating a distinct issue for that, but recognize that any proposal to add `<titlealts>` in maps will have to address whether `@locktitle` continues to exist.

**Comment by robertnthomas** [comment]
Bob volunteered to review

**Comment by robander** [comment]
Discussed deadlines at TC today, Robert and Eliot need to review stage 2 proposal.

**Comment by ctnitchie** [comment]
Discussed on 3/Dec/2019 TC meeting. Due to unforseen issues encountered in Stage 3 development, going back to the Stage 2 drawing board.

**Comment by robander** [comment]
Stage 2 re-approved April 21, 2020.

Stage 3 approved February 9, 2021.
