### ISSUE TITLE
Element for referencing subject scheme map

### ISSUE THREAD

**Issue by robander** [oasis-tcs/dita#163]
Based on email from Deb: https://lists.oasis-open.org/archives/dita/201808/msg00043.html 

Discussed at TC meeting August 21, 2018. Consensus toward moving existing `<schemeref>` out of subject scheme and into mapgroup; OASIS shells for subject scheme already include the mapgroup domain, but this is technically backwards incompatible with existing subject scheme shells that do not include the domain.

Also need to clean up the overall definition of `<schemeref>` to make it more general, right now it is only allowed at top level of subject scheme and has special rules about how to merge the referenced scheme.

**Comment by robander** [comment]
Briefly discussed August 20, 2019, Kris and Deb to discuss possibilities.

**Comment by keberlein** [comment]
Minutes for 21 August 2018 meeting: https://lists.oasis-open.org/archives/dita/201808/msg00050.html

**Comment by robander** [comment]
[Cleaning up old tracker issues] We decided at an earlier meeting not to move `schemeref` into mapgroup.
