### ISSUE TITLE
Redesign hazardstatement

### ISSUE THREAD

**Issue by robander** [oasis-tcs/dita#164]
Request from Dawn, submitted back in May. May be combined with (or overlap) general redesign work on hazard domain that Jang has proposed.

Kris and Dawn likely to end up working on this together.

**Comment by keberlein** [comment]
Discussed at TC meetings on 15 May, 05 June, and 04 December 2018. Relevant sections of meetings in the attached PDF file (which provides hyperlinks to TC e-mails).
[hazardStatementRedesign.pdf](https://github.com/oasis-tcs/dita/files/3529990/hazardStatementRedesign.pdf)

**Comment by robander** [comment]
Stage 3 proposal approved Oct 22, 2019
