### ISSUE TITLE
Resolve inconsistent class values for shortdesc, linktext, searchtitle

### ISSUE THREAD

**Issue by robander** [oasis-tcs/dita#21]
For historical reasons, the three elements have duplicate `@class` attribute definitions. Details and original stage 1 proposal to fix this are here:
https://lists.oasis-open.org/archives/dita/201705/msg00006.html

Discussed at TC meeting May 9, 2017; agreed to move forward to stage 2 and assigned to Eliot Kimber. Expecting that the `map/*` class attributes will be removed in 2.0, so that each of these three uses only the `topic/*` variant in all cases.

Discussed Jan 9 2018: aiming for stage 2 complete by February 26. 
  
06 Feb 2018: Robert Anderson assigned as reviewer

27 Feb 2018: move stage 2 due date to March 13

14 May 2019: discussed at TC and moved to stage 3.

**Comment by keberlein** [comment]
Link to minutes for the 9 May 2017 meeting: https://lists.oasis-open.org/archives/dita/201705/msg00022.html

**Comment by drmacro** [comment]
Starting work on this.

**Comment by keberlein** [comment]
Targeted for 12 June 2018.

**Comment by drmacro** [comment]
Stage 2 source is in SVN. Have reminded Robert that he is a reviewer.

**Comment by drmacro** [comment]
Integrated Robert's review comments and committed update to SVN

**Comment by drmacro** [comment]
Stage 2 proposal loaded to Kavi and reported to TC mailing lis.

**Comment by drmacro** [comment]
Stage 3 draft commited to SVN and ready for review.

**Comment by drmacro** [comment]
Created provisional pull request with RNG grammar changes. Will  update or replace pull request once stage 3 proposal is approved.

**Comment by drmacro** [comment]
Reviewers for stage 3:
Zoe Lawson
Deb Bissantz

**Comment by drmacro** [comment]
Review PDF sent to reviewers.

**Comment by drmacro** [comment]
Received review comments from Deb Bissantz. Updated DITA source to reflect Deb's comments.

**Comment by drmacro** [comment]
Received review comments from Zoe Lawson (17 Oct 2019)
Prepared final draft and provided to TC for consideration.

**Comment by robander** [comment]
Stage 3 proposal approved at TC meeting Oct 29, 2019.
