### ISSUE TITLE
Redesign how grammar files are structured for delivery

### ISSUE THREAD

**Issue by robander** [oasis-tcs/dita#22]
Discussed at TC May 9, 2017, and at some earlier meetings.

Robert suggested a goal that will give us a stronger focus on RNG as the main delivery format for modular grammar files, and remove the requirement (or even the suggestion) that DTD or XSD implementations must be modular to comply with the spec. Going into the future, best practice as laid out by the TC would be to maintain grammar files in RNG, and generate monolithic DTD or XSD as needed for applications that do not use RNG.

There are open questions remaining after the May 9 meeting:

- Should OASIS deliver modular DTD files with 2.0 (as opposed to monolithic DTDs)? Pro: it will allow existing DTD users to upgrade more easily, and shift to RNG over time. Con: additional maintenance burden on the TC could slow down development, and uncertain if tools will be able to fully automate this.
- There is general agreement on _not_ shipping modular XSD files. Should OASIS deliver monolithic XSD versions of the grammar files? Pro: at least a few editors currently require XSD and could use it. Con: additional time to generate and test will cause some amount of delay.

**Comment by keberlein** [comment]
Link to minutes for 9 May 2017:
https://lists.oasis-open.org/archives/dita/201705/msg00022.html

**Comment by gershonj** [comment]
Would this redesign fix the current inability to constrain content models in RNG? In order to constrain an existing element's contents, one needs to change the base module. This is not how DITA constraints are supposed to work -- one should never ever have to constrain the base definition provided with the spec...

**Comment by robander** [comment]
@gershonj I don't think this item (as discussed so far) would impact how constraints are created.

That said, I did not think that RNG constraints required that you modify the base module files, it's done by overriding rather than by changing.

**Comment by robander** [comment]
Marking this closed - I think these decisions have already been made (we are still maintaining modular DTD files, and not shipping XSD). The busy work of fixing up file names / directories is covered under #170.
