### ISSUE TITLE
Make Learning and Training a separate work product

### ISSUE THREAD

**Issue by keberlein** [oasis-tcs/dita#31]
Discussed at TC meeting on 21 March 2017:
https://lists.oasis-open.org/archives/dita/201703/msg00025.html

**Comment by keberlein** [comment]
Discussed at TC meeting on 16 May 2017:
https://lists.oasis-open.org/archives/dita/201705/msg00048.html

**Comment by robander** [comment]
Splitting base so that it will be published independently of L&T (with technical communications also independent) was approved at TC meeting 13 March 2018.
