### ISSUE TITLE
Deprecate or remove copy-to attribute

### ISSUE THREAD

**Issue by robander** [oasis-tcs/dita#33]
Discussed at TC May 30, 2017. Those on call currently favor removing the attribute and when similar function is needed, using key values in its place. Moved to stage 2 and assigned to Eliot.
  
Discussed Jan 9 2018: aiming for stage 2 proposal by March 26.

06 Feb 2018: Stan Doherty assigned as reviewer

**Comment by keberlein** [comment]
Minutes from 30 May 2017:
https://lists.oasis-open.org/archives/dita/201706/msg00013.html

**Comment by keberlein** [comment]
Targeted for 12 June 2018.

**Comment by drmacro** [comment]
I have drafted the stage 2 proposal, committed it to SVN, and sent to Robert and Chris N. for review.

**Comment by drmacro** [comment]
I have reviewed the feedback from Robert and Chris. 
Based on their feedback I need to rewrite the proposal to make it much simpler.
I will attempt to have that rework back in the revewers' hands fofore the 8/27 meeting.

**Comment by drmacro** [comment]
Have updated the stage 2 proposal, committed update to SVN and provided to reviewers for review.

**Comment by drmacro** [comment]
Final stage 2 proposal committed to SVN and submitted to TC for promotion to stage 3.

**Comment by drmacro** [comment]
Added additional discussion to example. Updated in SVN, posted PDF to TC mailing list.

**Comment by drmacro** [comment]
Received detailed comments from Kris. Have started reworking to reflect her comments.

**Comment by drmacro** [comment]
Finally did the update to the stage 2 proposal. Committed to SVN and PDF uploaded to cavi, HTML posted to dita mailing list.

**Comment by drmacro** [comment]
Updated draft to reflect review comments, posted to dita mailing list, committed to SVN, PDF loaded to cavi.

**Comment by robander** [comment]
Moved to stage 3 during TC meeting Feb 2, 2021

**Comment by drmacro** [comment]
First draft of Stage 3 proposal sent to reviewers 15 March 2021

**Comment by drmacro** [comment]
Updated grammar files to remove @copy-to and add appid-role.

Created merge request that includes grammar changes and spec file changes.

**Comment by robander** [comment]
Stage 3 approved at TC May 11, 2021

**Comment by robander** [comment]
Completed with the many pull requests linked above
