### ISSUE TITLE
Remove topicset and topicsetref

### ISSUE THREAD

**Issue by robander** [oasis-tcs/dita#34]
Discussed at TC May 30, 2017. Consensus is that these elements seem to provide very little value over ordinary `<topicref>` elements. In addition, they regularly suggest to authors that they should result in some sort of standard special processing (which they do not). Proposal moved to stage 2 and assigned to Eliot. 
  
Discussed Jan 9 2018: aiming for stage 2 proposal done by Feb 26

06 Feb 2018: Tom Magliery assigned as reviewer

27 Feb 2018: move stage 2 due date to March 13

14 May 2019: discussed at TC and moved to stage 3.

**Comment by keberlein** [comment]
Minutes from 30 June 2017:
https://lists.oasis-open.org/archives/dita/201706/msg00013.html

**Comment by drmacro** [comment]
Proposal drafted, grammar files updated, spec files updated. Pushed to feature branch  feature/proposal-34-remove-topicset

**Comment by drmacro** [comment]
Pull request created for grammar and spec changes.

**Comment by keberlein** [comment]
Targeted for 12 June 2018.

**Comment by cyrilanderson** [comment]
Robert,
Thanks for the incredibly quick and detailed response. That was very useful, and much appreciated. 
The existing Oasis docs kind of touch on this point of the flexibility of targets types for topicref, but not as clearly as you laid it out here. 

Follow-up question to check that I understand you properly.

To build on the example you've given. Suppose my other.ditamap file looks something like the following:

```
<map>
...
<topicref id="installingBranch" href="system_B_installation_overview.dita">
    <topicref href="system_B_physical_mounting.dita"/>
    <topicref href="system_B_power_integration.dita"/>
    <topicref href="system_B_controls_integration.dita"/>
</topicref>
...
</map>
```
So the installation section has 4 topics, an overview and 3 more detailed topics nested within as child elements in the map. 

So in the second map where you want to reuse that block of content,  
`<topicref href="other.ditamap#installingBranch" format="ditamap"/>` will
pull in the whole block of content, including the child topics? 

Which, actually, yes, that makes sense. The inner topicrefs are content of the outer one.

In that case, I guess I'd tend to agree with you about topicset and topicsetref being redundant.

Once again, greatly appreciate your time. Learned something new, which always makes for a good day !

**Comment by robander** [comment]
> Follow-up question to check that I understand you properly.

@cyrilanderson yep, you got it right. In the end it's not much different than using `@conref` to pull the branch, so really you could go with either. Basically it's just realizing that "Referencing a map = use that map" so it generally follows that referencing a branch of a map in the same way = use that branch of the map.

**Comment by drmacro** [comment]
Stage 2 proposal added to Kavi and submitted to TC for discussion.

**Comment by drmacro** [comment]
Stage 3 reviewers: Kris Eberlein, Bill Burns.

**Comment by drmacro** [comment]
Review copy sent to reviewers 2 Sept 2019

**Comment by drmacro** [comment]
Submitted to TC for discussion 15 Sept 2019

**Comment by drmacro** [comment]
Updated stage 3 proposal added to SVN and submitted to TC per proposal process.

**Comment by drmacro** [comment]
Approved at stage 3 by voice vote of the TC 8 Oct 2019
