### ISSUE TITLE
Remove "fastpath" value from note/@type

### ISSUE THREAD

**Issue by robander** [oasis-tcs/dita#35]
Discussed February 21, 2017: 
https://lists.oasis-open.org/archives/dita/201702/msg00054.html

Discussed again May 30, 2017.

This value is very rarely used and often seen as an odd part of DITA, that does not fit with other values for `note/@type`. There was a wider question about whether or not we should examine other values, and/or remove the enumerated values so that anybody could create new `note/@type` values (and would optionally need to use a subject scheme to restore the current standard values), but the original focus is on `fastpath`.

**Comment by robander** [comment]
Just a curious note: as of today, if you search the entire email archives of the OASIS DITA TC, the only result in our 12 or 13 years of email is the set of meeting notes from February 21.

**Comment by keberlein** [comment]
Minutes from 30 May 2017:
https://lists.oasis-open.org/archives/dita/201706/msg00013.html

**Comment by robander** [comment]
Moved to stage 2 March 3 2020 with Keith as owner.

**Comment by robander** [comment]
Stage two approved 24 March https://lists.oasis-open.org/archives/dita/202003/msg00045.html

**Comment by Schelmenzunft** [comment]
Hi there at OASIS DITA team,

just saw this and must confess that I can’t find any reason for removing this element.

Note has 13 types + use-conref-target. Why delete this one? We use it in our software documentation and it’s nicely rendered with a rocket bitmap in Oxygen’s Webhelp.

And it visually stands out in a topic:

[cid:image002.jpg@01D6A852.6048B290]

Our writers have trouble to decide when to use attention, caution, danger, trouble, warning – but we defined a business rule and don’t suggest the DITA committee to change the standard.

So if it’s not too late I beg you to reconsider …

Greetings from Home-Office in S/W Germany,

Franz-Josef





AKG Software Consulting GmbH
Franz-Josef Knelangen


Uhlandstraße 12
79423 Heitersheim
Germany

Tel.: +49 (0)7634 5612-611
Fax: +49 (0)7634 5612-300
E-Mail: fjk@akgsoftware.de
Internet: www.akgsoftware.de<http://www.akgsoftware.de>

Geschäftsführer: Dipl.-Ing. Artur K. Günther, Dipl.-Ing. Arno Brüggemann, Dipl.-Ing. (FH) Bernhard Feser, Dipl.-Ing. Jens Günther
Sitz der Gesellschaft: Heitersheim, HRB 310383 (Amtsgericht Freiburg)

Von: Robert D Anderson <notifications@github.com>
Gesendet: Donnerstag, 22. Oktober 2020 05:30
An: oasis-tcs/dita <dita@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [oasis-tcs/dita] Remove "fastpath" value from note/@type (#35)



Externe E-Mail: Vorsicht beim Öffnen von Anhängen und Klicken auf Links!


Stage two approved 24 March https://lists.oasis-open.org/archives/dita/202003/msg00045.html

**Comment by robander** [comment]
@Schelmenzunft Thanks for the feedback - I've let the TC know about your comments, so it will come up again soon at one of our meetings. I'll update again here after that discussion.

**Comment by robander** [comment]
@Schelmenzunft I raised this at the TC meeting today, after sending this email:
https://lists.oasis-open.org/archives/dita/202010/msg00046.html

Based on today's discussion, we will quietly forget the original plan to remove this value, so it will still be part of DITA 2.0. Thanks for jumping in quickly when you got the notification, it was just in time...
