### ISSUE TITLE
[dita-comment] @keyref attribute is not defined for msgph, userinput, systemoutput and filepath in softwareDomain.mod

### ISSUE THREAD

**Issue by ToshihikoMakita** [oasis-tcs/dita#366]
Following is posted into [dita-comment] mailing-list on July, 1 2020. However there is no reply from TC members at this moment (July 10). If it contains any misunderstanding about DITA specification and/or DTDs, please let me know.

Subject: | [dita-comment] @keyref attribute is not defined for msgph, userinput, systemoutput and filepath in softwareDomain.mod
-- | --
Wed, 1 Jul 2020 21:23:17 +0900
Toshihiko Makita <tmakita@antenna.co.jp>
dita-comment@lists.oasis-open.org <dita-comment@lists.oasis-open.org>

Hi List,

If this is already reported or known problem, please forgive me.

One of our user reported that <msgph>, <userinput>, <systemoutput> and <filepath> in Software Domain should have @keyref attribute according to the DITA 1.3 specification.

> The following attributes are available on this element: Universal 
attribute group , outputclass, and @keyref .

3.10.7.6.1 <msgph>
http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/langRef/technicalContent/msgph.html#msgph

3.10.7.6.7 <userinput>
http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/langRef/technicalContent/userinput.html#userinput

3.10.7.6.8 <systemoutput>
http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/langRef/technicalContent/systemoutput.html#systemoutput

3.10.7.6.6 <filepath>
http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/langRef/technicalContent/filepath.html#filepath

However when this user authors @keyref attribute for these elements, the XML Editor (oXygen) reports validation error for the next sample data.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE concept PUBLIC "-//OASIS//DTD DITA Concept//EN" "concept.dtd">
<concept id="cSoftwareDomain" xml:lang="en-US">
    <title>Software Domain</title>
    <shortdesc>Testing software domain keyref function.</shortdesc>
    <conbody>
        <p>This <xmlelement>msgph</xmlelement> uses <xmlatt>keyref</xmlatt> attribute: <msgph keyref="NOTE"/></p>
        <p>This <xmlelement>userinput</xmlelement> uses <xmlatt>keyref</xmlatt> attribute: <userinput keyref="NOTE"/></p>
        <p>This <xmlelement>systemoutput</xmlelement> uses <xmlatt>keyref</xmlatt> attribute: <systemoutput keyref="NOTE"/></p>
        <p>This <xmlelement>filepath</xmlelement> uses <xmlatt>keyref</xmlatt> attribute: <filepath keyref="OT_PATH"/></p>
    </conbody>
</concept>

E [Xerces] Attribute "keyref" is not allowed to appear in element "msgph".
E [Xerces] Attribute "keyref" is not allowed to appear in element "userinput".
E [Xerces] Attribute "keyref" is not allowed to appear in element "systemoutput".
E [Xerces] Attribute "keyref" is not allowed to appear in element "filepath".

I have analyzed relevant DTD file and found that @keyref attribute is not defined for these elements in softwareDomain.mod file.

https://github.com/oasis-tcs/dita/blob/hotfix/DITA-1.3_Errata03/doctypes/dtd/technicalContent/dtd/softwareDomain.mod

https://github.com/dita-ot/dita-ot/blob/develop/src/main/plugins/org.oasis-open.dita.v1_3/dtd/technicalContent/dtd/softwareDomain.mod

If this is the bug, early fix is much appreciated.

Regards,

-- 
/*--------------------------------------------------
 Toshihiko Makita
 Development Group. Antenna House, Inc. Ina Branch
 E-Mail tmakita@antenna.co.jp
 8077-1 Horikita Minamiminowa Vil. Kamiina Co.
 Nagano Pref. 399-4511 Japan
 Tel +81-265-76-9300 Fax +81-265-78-1668
 Web site:
 http://www.antenna.co.jp/
 http://www.antennahouse.com/
 --------------------------------------------------*/
-- 
This publicly archived list offers a means to provide input to the
OASIS Darwin Information Typing Architecture (DITA) TC.

In order to verify user consent to the Feedback License terms and
to minimize spam in the list archive, subscription is required
before posting.

Subscribe: dita-comment-subscribe@lists.oasis-open.org
Unsubscribe: dita-comment-unsubscribe@lists.oasis-open.org
List help: dita-comment-help@lists.oasis-open.org
List archive: http://lists.oasis-open.org/archives/dita-comment/
Feedback License: http://www.oasis-open.org/who/ipr/feedback_license.pdf
List Guidelines: http://www.oasis-open.org/maillists/guidelines.php
Committee: http://www.oasis-open.org/committees/tc_home.php?wg_abbrev=dita
Join OASIS: http://www.oasis-open.org/join/

**Comment by robander** [comment]
Follow-up from list: https://lists.oasis-open.org/archives/dita-comment/202007/msg00001.html

At our next meeting we agreed to treat this as a fix: https://lists.oasis-open.org/archives/dita/202008/msg00000.html

**Comment by robander** [comment]
It looks like that fix has not yet been incorporated, so keeping this open

**Comment by robander** [comment]
This fix has been merged to the DITA 2.0 vocabulary: https://github.com/oasis-tcs/dita-techcomm/pull/118
