### ISSUE TITLE
"-//OASIS//DTD DITA Message Reference//EN"?

### ISSUE THREAD

**Issue by GrahamHannington** [oasis-tcs/dita#382]
Is "-//OASIS//DTD DITA Message Reference//EN" a genuine [Formal Public Identifier](http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/non-normative/dtd-public-identifiers.html#dtd-public-identifiers) (FPI)? Specifically, with OASIS as the owner identifier?

I think the answer is no, but I'd like to have that confirmed, preferably by a TC member.

I've seen that exact string, with that owner identifier, in use as an FPI, but I think it's a bogus confection; at best, wishful thinking. Please don't ask me where. I will decline to answer.

In IBM-brand product documentation, I've used the IBM message reference specialization identified by the FPI "-//IBM//DTD DITA Message Reference//EN"; that is, with the owner identifier IBM, not OASIS.

I've seen a reference to a non-IBM DITA message reference DTD in the [IXIASOFT documentation](http://archive.ixiasoft.com/en/products/dita-cms/documentation/4-1/integrating-dtds-dita-cms/creating-custom-dtd-plugin/creating-custom-dtd-plugin-system-configuration/edit-system-ids), following the comment  "ACME Specializations", with COMPANY as the owner identifier, and `CompanyMsgRef.dtd` as the DTD file name.

I'm curious: does that reference in the IXIASOFT docs reflect a tacit adoption of that specialization by companies outside IBM? I spend much of my time using the IBM documentation toolchain to develop IBM-brand product documentation; I'm less familiar with DITA use outside of that context. It makes sense to me that companies that develop their own-brand products for IBM platforms, where users might be familiar with the way that IBM products document messages, might wish to present message documentation in similar fashion to IBM. It also makes sense to me that IBM might wish to promote that practice (I'm happy to expand on this topic, if asked).

Has there ever been a proposal to add the IBM message reference specialization to the OASIS DITA standard? I'd be interested in any history about that.

**Comment by GrahamHannington** [comment]
DITA 1.2 spec section B.7, "[DTD organization](https://docs.oasis-open.org/dita/v1.2/os/spec/non-normative/dtdorganization.html)" contains the heading "Public identifiers for DTDs", which lists identifiers that "are declared by the DITA Technical Committee for modules that are shipped with the DITA 1.2 distribution". That list does not include a "Message Reference".

DITA 1.3 spec section B.7, "[DTD public identifiers](http://docs.oasis-open.org/dita/dita/v1.3/errata02/os/complete/part3-all-inclusive/non-normative/dtd-public-identifiers.html)", does not contain an equivalent list.

**Comment by keberlein** [comment]
Graham, the message specialization developed by IBM and made available on SourceForge has never been part of the OASIS distribution. No one has ever suggested that it become part of the DITA standard. As chair of the DITA Technical Committee, I can assure you that any such suggestion will not be supported by the TC.

**Comment by GrahamHannington** [comment]
@keberlein ,

Thank you so much for the quick, unequivocal answer. I could not have asked for a clearer, more informative response. :+1:

> the message specialization developed by IBM ... has never been part of the OASIS distribution. 

Yes, that matches what I thought.

> No one has ever suggested that it become part of the DITA standard. As chair of the DITA Technical Committee, I can assure you that any such suggestion will not be supported by the TC.

Good to know. In case it occurred to you: I wasn't considering suggesting it 🙂 . I was just digging for history on why someone might have coined that bogus FPI.

> made available on SourceForge

I didn't know about that. That's interesting and useful. I was unaware that this specialization had been made available on the public web. (As you say, on SourceForge: Development / Text Processing / DITA Open Toolkit / Files / [Plug-in_message specialization](https://sourceforge.net/projects/dita-ot/files/Plug-in_message%20specialization/).)

Thanks again!

**Comment by GrahamHannington** [comment]
I've just downloaded that specialization from SourceForge. From the supplied `msgRef.dtd` file:

````xml
<!--  Refer to this file by the following public identfier or an 
      appropriate system identifier 
PUBLIC "-//OASIS//DTD DITA Message Reference//EN"
      Delivered as file "msgRef.dtd"                            -->
````
("identfier", sic)

While I'm sincerely grateful to IBM for making this specialization publicly available, and I wouldn't want it removed, I think that comment offers bad advice.

(I note that the supplied catalog and sample DITA topic files refer to the "IBM" FPI.)

**Comment by GrahamHannington** [comment]
Argh. I've compared the publicly available `msgRef.dtd` from SourceForge with the file of the same name in my IBM-supplied toolchain. Without revealing any proprietary information: the files are different. Some of the differences involve references, in the version supplied with the IBM toolchain, to other IBM-only specializations.

So, while I understand that "OASIS" is an incorrect choice of owner identifier for the publicly available `msgRef.dtd`, I'm not so sure that I want use the _same_ FPI for _different_ `msgRef.dtd` files.

I understand that, if non-IBM and IBM-brand message topics are always processed in separate environments, where the URI resolver in each environment resolves the same FPI to the appropriate `msgRef.dtd` file, then, in practice, this doesn't matter.

Still, I don't like the ambiguity; the potential for confusion; perhaps, the possibility for validation errors.

I'd appreciate advice on what FPI to use for the publicly available `msgRef.dtd` file. Not the "-//OASIS//DTD DITA Message Reference//EN" recommended in that comment I quoted, because this specialization is not owned by OASIS, and not the original "-//IBM//DTD DITA Message Reference//EN", either, because that's the FPI for the different IBM-use-only version of that file (and I'm not about to suggest IBM uses a different FPI for that!). Or just: move on, don't worry about it?

**Comment by keberlein** [comment]
If you are going to use the message specialization from SourceForge, create your own company-specific document-type shell and public identifier. Use standard DITA best practices. If you are not going to use the specialization, move on :)

**Comment by GrahamHannington** [comment]
All sound advice, thank you! 🙂
