### ISSUE TITLE
Remove xtrc and xtrf attributes from list of global attributes

### ISSUE THREAD

**Issue by robander** [oasis-tcs/dita#46]
The xtrc and xtrf attributes were added to all elements in DITA 1.0. They are entirely intended for processing purposes, with a DITA-OT style processing model in mind. Specifically, the expectations were that:

1. Processors would read/write DITA files as they evaluated features like `@conref` (as DITA-OT has done since early days in the temporary directory)
1. Processors needed to a place to track source information to enable later debugging (this has been done by some processors with `@xtrf` and `@xtrc` since DITA beta days)
1. DITA had to remain valid during every read/write in the temp directory, including with this debug information (DITA-OT has never followed this and will not in the future; I only know of one tool in beta DITA days that had this requirement)
1. Because processed DITA with debug info had to be valid, every DITA element needed to declare xtrf/xtrc.

The DITA specification (in the last couple of releases) has shied away from adding functionality or markup based on what is done with processed DITA -- that is, it uses DTD / RNG to place rules on the source, but once processors start working with it, that is up to processors. 

Given that, some TC members have suggested that the xtrc / xtrf attributes are no longer appropriate for the standard itself, because the use cases that prompted them are no longer valid -- there is nothing inherent in DITA that would require applications to write out `xtrf/xtrc` as part of a validating DITA document.

Original email thread to TC, June 14 2016: https://lists.OASIS-open.org/archives/dita/201606/msg00013.html

Discussed as Stage 1 proposal 19 July 2017, discussed further on July 11, 2017.
  
Discussed Jan 9, aiming for stage 2 proposal complete by end of Jan

Discussed at TC meeting on 06 Feb 2018: https://lists.oasis-open.org/archives/dita/201802/msg00035.html

Voted to stage 3 on 13 Feb 2018.

Initial stage 3 proposal sent to TC 6 March 2018 after review from Kris and Carsten: https://lists.oasis-open.org/archives/dita/201803/msg00016.html

**Comment by robander** [comment]
Officially moved to Stage 2 list at TC meeting August 22, 2017.

**Comment by keberlein** [comment]
Discussed at TC meeting on 06 Feb 2018: https://lists.oasis-open.org/archives/dita/201802/msg00035.html

**Comment by robander** [comment]
Approved at stage 3 for DITA 2.0, 13 March 2018.
