### ISSUE TITLE
Remove "delayed conref domain" from DITA 2.0

### ISSUE THREAD

**Issue by robander** [oasis-tcs/dita#73]
Proposal to remove "delayed conref domain" from DITA 2.0. The domain added three elements in DITA 1.2. Based on informal polling, it does not appear to be used, and many do not know what the three elements are for. Suggest removing from DITA 2.0 as part of effort to simplify the language and remove features that are not needed.

Discussed at TC Sept 5 2017 and assigned as stage 1 to Alan Houser.

Based on email thread begun by Kris:
https://lists.oasis-open.org/archives/dita/201708/msg00056.html

Moved to stage 2 at TC Sept 19 2017 with Alan Houser as owner.

Discussed Jan 9 2018: aiming to complete Stage 2 proposal by Jan 29

06 Feb 2018: Stan Doherty assigned as reviewer.

Voted Feb 20 to move from Stage 2 to Stage 3.

**Comment by ahouser** [comment]
Stage 2 proposal available for TC review at [https://www.oasis-open.org/apps/org/workgroup/dita/download.php/62461/delayed_conref.html](url)

**Comment by ahouser** [comment]
Stage 2 proposal available for TC review at [https://www.oasis-open.org/apps/org/workgroup/dita/download.php/62461/delayed_conref.html](url)

**Comment by ahouser** [comment]
Stage 2 proposal available for TC review at https://www.oasis-open.org/apps/org/workgroup/dita/download.php/62461/delayed_conref.html

**Comment by ahouser** [comment]
I've revised the stage 2 proposal based on comments by @robander (thanks!). Revision for TC review is at [https://www.oasis-open.org/apps/org/workgroup/dita/download.php/62481/latest/delayed_conref_revised.html](https://www.oasis-open.org/apps/org/workgroup/dita/download.php/62481/latest/delayed_conref_revised.html)

**Comment by ahouser** [comment]
Stage 3 proposal available at -- https://www.oasis-open.org/committees/document.php?document_id=63270&wg_abbrev=dita. Reviewed by Kris and Robert; changes incorporated.

**Comment by ahouser** [comment]
Revised Stage 3 proposal with updated title (replaced "Deprecate" with "Remove"). 
https://www.oasis-open.org/apps/org/workgroup/dita/download.php/63319

**Comment by robander** [comment]
To finish up record keeping here, the stage 3 proposal from June 18 was approved on June 26: https://lists.oasis-open.org/archives/dita/201806/msg00057.html

**Comment by robander** [comment]
Completed with #171.
