### ISSUE TITLE
Add a new vocabulary element for inclusion of external XML and text markup

### ISSUE THREAD

**Issue by keberlein** [oasis-tcs/dita#8]
See full description below based on request from @ctnitchie .

Discussed Jan 9 2018 -- need input from others before continuing with stage 2. Goal of February 26 to either get input + create stage 2 proposal, or to withdraw.

06 Feb 2018: Dick Hamilton assigned as reviewer

27 Feb 2018 discussed stage 2 proposal at TC.

13 March 2018 voted on stage 2 proposal, moved to stage 3.

Discussed 1 May 2018, Eliot and Robert agreed to be reviewers for stage 3 proposal.

**Comment by ctnitchie** [comment]
My initial e-mail to the list on this topic:

The `<coderef>` element is a transclusion element – it loads the referenced file and places its contents as CDATA at the location of the referencing element. However, `<coderef>` is a specialization of `<xref>`, which is not a transclusion element. That is, the specialization-based fallback behavior for `<coderef>` is fundamentally incompatible with the expected processing. The same is true for `svgref` and `mathmlref`. The only way for people other than the TC to create similar transclusion elements via specialization is to specialize from one of those, or customize their processors to do the right thing with their element.
 
For DITA 2.0, I suggest we add an <include> element to the base vocabulary to act as a base for specialization for these kinds of elements.
 
```
<include href=”uri” format=”format” parse=”xml|text”>
  <fallback>Fallback content here</fallback>
</include>

``` 
This is roughly modeled on xinclude, but without the need for the namespace, and with `@class` so it can be used as a base for specialization. (And, of course, `@keyref`-capable.)

**Comment by ctnitchie** [comment]
Robert and Eliot signed up as Stage 3 reviewers during the May 1 TC meeting.

**Comment by keberlein** [comment]
Approved to pass stage three
