### ISSUE TITLE
Strict task example does not match content model

### ISSUE THREAD

**Issue by james-bostock** [oasis-tcs/dita#82]
The "Task topic (strict task)" topic of the DITA specification (see the file [dita-task-topic.dita](https://github.com/oasis-tcs/dita/blob/master/specification/archSpec/technicalContent/dita-task-topic.dita)) contains an example task which contains the &lt;context&gt; and &lt;prereq&gt; elements in the wrong order.

**Comment by keberlein** [comment]
Yes, we are aware of this. It will be fixed in errata 02. Thanks for bringing it to our attention!

Kris
