### ISSUE TITLE
Add new element for change-historylist lists

### ISSUE THREAD

**Issue by xephon2** [oasis-tcs/dita#83]
Because the *release management* domain is an official DITA domain, there should be a dedicated `<booklists>` element for it. This is the currently suggested solution from @robander.

```xml
<frontmatter>
    <booklists>
        <toc/>
        <booklist type="change-historylist"/>
        <tablelist/>
    </booklists>
</frontmatter>
```

Something like this would be more elegant:

```xml
<frontmatter>
    <booklists>
        <toc/>
        <changelist/>
        <tablelist/>
    </booklists>
</frontmatter>
```

**Comment by robander** [comment]
If I remember correctly, when this came up in the TC, an alternate suggestion was to use `<amendments>` (without `@href`) as a way to indicate that a change history list should be generated. If that works, then we could also handle this (without adding a new element) by allowing `<amendments>` inside the current `<booklists>` model.

The general issue of a way to indicate you want a generated change history topic was moved to stage 2 in the DITA 2.0 proposal process today, with Scott Hudson as owner.

**Comment by xephon2** [comment]
This would work. However, `<amendments>` is no valid child of `<booklists>`. Maybe this should be changed. IMHO, the principle is the same as for the other `<booklists>` elements.

**Comment by robander** [comment]
:+1: Yes - if we go with that element as the answer for this issue in 2.0, it will have to be added to `<booklists>`

**Comment by robander** [comment]
Merging with #29 with the design discussed above -- `<amendments>` will be available both at its present location and in `<booklists>`, which will allow it to be used for generating a change history list in either the front or the back matter.
